# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'ToolUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
# 导入样式文件
from QSSwhite import QSS


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 4, 1241, 661))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_12.setGeometry(QtCore.QRect(320, 320, 535, 251))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setGeometry(QtCore.QRect(40, 30, 60, 24))
        self.label_4.setObjectName("label_4")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_1.setGeometry(QtCore.QRect(102, 30, 156, 24))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_1.setGeometry(QtCore.QRect(270, 26, 110, 32))
        self.radioButton_1.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/wilson/PYQT5/TMTools/Icon/e52d9567c015cdb440344305380739e7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_1.setIcon(icon)
        self.radioButton_1.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_2.setGeometry(QtCore.QRect(398, 26, 111, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/wilson/PYQT5/TMTools/Icon/b721a1c9956b6e836cbdb6c57691ef09.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_2.setIcon(icon1)
        self.radioButton_2.setIconSize(QtCore.QSize(22, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_1.setGeometry(QtCore.QRect(40, 70, 91, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/wilson/PYQT5/TMTools/Icon/ooopic_1494068712.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1.setIcon(icon2)
        self.pushButton_1.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_1.setObjectName("pushButton_1")
        self.label_5 = QtWidgets.QLabel(self.groupBox_12)
        self.label_5.setGeometry(QtCore.QRect(160, 72, 71, 24))
        self.label_5.setObjectName("label_5")
        self.progressBar_1 = QtWidgets.QProgressBar(self.groupBox_12)
        self.progressBar_1.setGeometry(QtCore.QRect(240, 75, 250, 20))
        self.progressBar_1.setProperty("value", 24)
        self.progressBar_1.setObjectName("progressBar_1")
        self.textEdit_1 = QtWidgets.QTextEdit(self.groupBox_12)
        self.textEdit_1.setGeometry(QtCore.QRect(40, 120, 455, 121))
        self.textEdit_1.setObjectName("textEdit_1")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_25.setGeometry(QtCore.QRect(320, 40, 601, 201))
        self.groupBox_25.setObjectName("groupBox_25")
        self.label_11 = QtWidgets.QLabel(self.groupBox_25)
        self.label_11.setGeometry(QtCore.QRect(50, 18, 471, 141))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_21.setGeometry(QtCore.QRect(320, 290, 535, 251))
        self.groupBox_21.setObjectName("groupBox_21")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEdit_2.setGeometry(QtCore.QRect(102, 30, 156, 24))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_21)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 60, 24))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_21)
        self.label_7.setGeometry(QtCore.QRect(160, 72, 71, 24))
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_21)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 70, 91, 30))
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_21)
        self.progressBar_2.setGeometry(QtCore.QRect(240, 75, 250, 20))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_21)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 120, 455, 121))
        self.textEdit_2.setObjectName("textEdit_2")
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_24.setGeometry(QtCore.QRect(290, 40, 601, 201))
        self.groupBox_24.setObjectName("groupBox_24")
        self.label_12 = QtWidgets.QLabel(self.groupBox_24)
        self.label_12.setGeometry(QtCore.QRect(50, 18, 471, 141))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_31 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_31.setGeometry(QtCore.QRect(330, 230, 631, 361))
        self.groupBox_31.setObjectName("groupBox_31")
        self.progressBar_3 = QtWidgets.QProgressBar(self.groupBox_31)
        self.progressBar_3.setGeometry(QtCore.QRect(240, 75, 250, 20))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_31)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 70, 91, 30))
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_31)
        self.label_8.setGeometry(QtCore.QRect(40, 30, 60, 24))
        self.label_8.setObjectName("label_8")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_31.setGeometry(QtCore.QRect(102, 30, 141, 24))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_31)
        self.textEdit_3.setGeometry(QtCore.QRect(40, 120, 455, 121))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_31)
        self.label_9.setGeometry(QtCore.QRect(160, 72, 71, 24))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_31)
        self.label_10.setGeometry(QtCore.QRect(277, 30, 68, 24))
        self.label_10.setObjectName("label_10")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_32.setGeometry(QtCore.QRect(350, 30, 141, 24))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_23.setGeometry(QtCore.QRect(340, 20, 601, 201))
        self.groupBox_23.setObjectName("groupBox_23")
        self.label_3 = QtWidgets.QLabel(self.groupBox_23)
        self.label_3.setGeometry(QtCore.QRect(50, 18, 471, 141))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/home/wilson/PYQT5/TMTools/White/Cho-Katsu Kome.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_F.setIcon(icon3)
        self.menu_F.setObjectName("menu_F")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenfile = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/home/wilson/PYQT5/TMTools/White/Archer.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenfile.setIcon(icon4)
        self.actionOpenfile.setObjectName("actionOpenfile")
        self.actionQiut = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/home/wilson/PYQT5/TMTools/White/Chief Chujo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQiut.setIcon(icon5)
        self.actionQiut.setObjectName("actionQiut")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("/home/wilson/PYQT5/TMTools/Icon/201752212221.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("/home/wilson/PYQT5/TMTools/Icon/2017522122216.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAuthor.setIcon(icon7)
        self.actionAuthor.setObjectName("actionAuthor")
        self.menu_F.addAction(self.actionOpenfile)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actionQiut)
        self.menu_H.addAction(self.actionAbout)
        self.menu_H.addSeparator()
        self.menu_H.addAction(self.actionAuthor)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_12.setTitle(_translate("MainWindow", "运行过程"))
        self.label_4.setText(_translate("MainWindow", "文件名称："))
        self.radioButton_1.setText(_translate("MainWindow", "天猫商品"))
        self.radioButton_2.setText(_translate("MainWindow", "京东商品"))
        self.pushButton_1.setText(_translate("MainWindow", "开始"))
        self.label_5.setText(_translate("MainWindow", "完成进度："))
        self.groupBox_25.setTitle(_translate("MainWindow", "Instruction"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>1、sign in everyday, if you don\'t break the ring,release yourself </p><p>2、Record your progress everyday, you will witness your success!</p><p>3、click violate if you break the ring, a little trick punishment</p><p>4、Inform your community or friends what is your trouble </p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Record Your Face"))
        self.groupBox_21.setTitle(_translate("MainWindow", "运行过程"))
        self.label_6.setText(_translate("MainWindow", "文件名称："))
        self.label_7.setText(_translate("MainWindow", "完成进度："))
        self.pushButton_2.setText(_translate("MainWindow", "开始"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Instruction"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>1、sign in everyday, if you don\'t break the ring,release yourself </p><p>2、Record your progress everyday, you will witness your success!</p><p>3、click violate if you break the ring, a little trick punishment</p><p>4、Inform your community or friends what is your trouble </p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sign in Daily"))
        self.groupBox_31.setTitle(_translate("MainWindow", "运行过程"))
        self.pushButton_3.setText(_translate("MainWindow", "开始"))
        self.label_8.setText(_translate("MainWindow", "文件名称："))
        self.label_9.setText(_translate("MainWindow", "完成进度："))
        self.label_10.setText(_translate("MainWindow", "图片文件夹："))
        self.groupBox_23.setTitle(_translate("MainWindow", "Instruction"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>1、sign in everyday, if you don\'t break the ring,release yourself </p><p>2、Record your progress everyday, you will witness your success!</p><p>3、click violate if you break the ring, a little trick punishment</p><p>4、Inform your community or friends what is your trouble </p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Violate"))
        self.menu_F.setTitle(_translate("MainWindow", "File"))
        self.menu_H.setTitle(_translate("MainWindow", "Help[H]"))
        self.actionOpenfile.setText(_translate("MainWindow", "Check folder"))
        self.actionOpenfile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQiut.setText(_translate("MainWindow", "Quit"))
        self.actionQiut.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAuthor.setText(_translate("MainWindow", "Author"))

        # 添加默认值
        self.lineEdit_1.setText("dsr_ids.txt")
        self.lineEdit_2.setText("link_ids.txt")
        self.lineEdit_31.setText("img_links.txt")
        self.lineEdit_32.setText("PICs")
        # 设置提示语
        for each in [self.lineEdit_1, self.lineEdit_2, self.lineEdit_31]:
            each.setToolTip("温馨提示：请先确认文件是否存在！")
        self.lineEdit_32.setToolTip("警告：请勿使用非法文件名称，否则程序会崩溃！")
        # 设置鼠标样式和提示语
        for each in [self.pushButton_1, self.pushButton_2, self.pushButton_3]:
            each.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        # 添加样式风格
        self.mystyle()

    def mystyle(self):
        qss = QSS()
        self.setStyleSheet(qss.White)


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    myui = Ui_MainWindow()
    myui.show()
    sys.exit(app.exec_())
